# Generated by Django 3.1.4 on 2020-12-07 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manager', '0013_auto_20201205_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='likes2',
            field=models.ManyToManyField(related_name='like_comment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='likebookuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_book_table', to=settings.AUTH_USER_MODEL),
        ),
    ]
